### ISSUE TITLE
hey uhhhh

### ISSUE THREAD

**Issue by 7tfdfwdtfydgdy** [PixelGuy123/EditorCustomRooms#1]
i stuck at loading screen when i install this

**Comment by PixelGuy123** [comment]
Have you installed properly the assets of the plugin? They must be in BALDI_Data/StreamingAssets/Modded

**Comment by 7tfdfwdtfydgdy** [comment]
but it says pixelguy.pixelmodding.baldiplus.bbextracontent

**Comment by PixelGuy123** [comment]
That's from Baldi's Basics Times. Try updating the PixelInternalAPI then.

**Comment by 7tfdfwdtfydgdy** [comment]
i already update it

**Comment by PixelGuy123** [comment]
What error does it log in the console? Or Player.log?
