### ISSUE TITLE
Stuck At Loading Screen

### ISSUE THREAD

**Issue by MiloMiko** [PixelGuy123/EditorCustomRooms#2]
@PixelGuy123 please don't ask me about the Pixel API or the location of files. All of them are in place. I don't know what to do.
I read the previous issue and nothing worked. Please help. I just wand to play baldi's basics times :(

**Comment by PixelGuy123** [comment]
Make sure to use EditorCustomRooms 1.0.2, 1.0.3 is not compatible with BB Times yet

**Comment by MiloMiko** [comment]
Where do you install 1.0.2? On this page, there's only one full mod file and two for source code.

**Comment by MiloMiko** [comment]
Sorry, found it.

**Comment by MiloMiko** [comment]
Thank You!!!! It worked!!!!
